// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: workflow.proto

package workflow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentWorker_ExecuteTask_FullMethodName = "/zgentflow.AgentWorker/ExecuteTask"
)

// AgentWorkerClient is the client API for AgentWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentWorkerClient interface {
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type agentWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWorkerClient(cc grpc.ClientConnInterface) AgentWorkerClient {
	return &agentWorkerClient{cc}
}

func (c *agentWorkerClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, AgentWorker_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentWorkerServer is the server API for AgentWorker service.
// All implementations must embed UnimplementedAgentWorkerServer
// for forward compatibility.
type AgentWorkerServer interface {
	ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error)
	mustEmbedUnimplementedAgentWorkerServer()
}

// UnimplementedAgentWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWorkerServer struct{}

func (UnimplementedAgentWorkerServer) ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedAgentWorkerServer) mustEmbedUnimplementedAgentWorkerServer() {}
func (UnimplementedAgentWorkerServer) testEmbeddedByValue()                     {}

// UnsafeAgentWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWorkerServer will
// result in compilation errors.
type UnsafeAgentWorkerServer interface {
	mustEmbedUnimplementedAgentWorkerServer()
}

func RegisterAgentWorkerServer(s grpc.ServiceRegistrar, srv AgentWorkerServer) {
	// If the following call panics, it indicates UnimplementedAgentWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWorker_ServiceDesc, srv)
}

func _AgentWorker_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorker_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServer).ExecuteTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentWorker_ServiceDesc is the grpc.ServiceDesc for AgentWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zgentflow.AgentWorker",
	HandlerType: (*AgentWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _AgentWorker_ExecuteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
