// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务执行结果状态
type TaskStatus int32

const (
	TaskStatus_STATUS_UNKNOWN   TaskStatus = 0
	TaskStatus_STATUS_SUCCESS   TaskStatus = 1 // 顺利完成
	TaskStatus_STATUS_FAILED    TaskStatus = 2 // 执行失败（代码错误或 LLM 崩溃）
	TaskStatus_STATUS_TOOL_CALL TaskStatus = 3 // 请求 Flow 引擎执行本地工具（比如读写文件）
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_SUCCESS",
		2: "STATUS_FAILED",
		3: "STATUS_TOOL_CALL",
	}
	TaskStatus_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_SUCCESS":   1,
		"STATUS_FAILED":    2,
		"STATUS_TOOL_CALL": 3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

// 引擎生命周期事件（用于 EventStore 落盘和断点续传）
type EventType int32

const (
	EventType_EVENT_UNKNOWN            EventType = 0
	EventType_EVENT_WORKFLOW_STARTED   EventType = 1 // 收到请求，DAG 开始流转
	EventType_EVENT_TASK_SCHEDULED     EventType = 2 // 任务进入工作池，准备通过 gRPC 发给 Agent
	EventType_EVENT_TASK_COMPLETED     EventType = 3 // Agent 成功返回，任务完成
	EventType_EVENT_TASK_FAILED        EventType = 4 // Agent 返回失败或发生网络超时
	EventType_EVENT_WORKFLOW_COMPLETED EventType = 5 // DAG 图中所有节点执行完毕
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "EVENT_WORKFLOW_STARTED",
		2: "EVENT_TASK_SCHEDULED",
		3: "EVENT_TASK_COMPLETED",
		4: "EVENT_TASK_FAILED",
		5: "EVENT_WORKFLOW_COMPLETED",
	}
	EventType_value = map[string]int32{
		"EVENT_UNKNOWN":            0,
		"EVENT_WORKFLOW_STARTED":   1,
		"EVENT_TASK_SCHEDULED":     2,
		"EVENT_TASK_COMPLETED":     3,
		"EVENT_TASK_FAILED":        4,
		"EVENT_WORKFLOW_COMPLETED": 5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

type WorkflowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowID    string                 `protobuf:"bytes,1,opt,name=workflowID,proto3" json:"workflowID,omitempty"`
	TaskID        string                 `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	EventType     EventType              `protobuf:"varint,3,opt,name=eventType,proto3,enum=zgentflow.EventType" json:"eventType,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // Agent 跑出来的代码或报错日志，直接存 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEvent) Reset() {
	*x = WorkflowEvent{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEvent) ProtoMessage() {}

func (x *WorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEvent.ProtoReflect.Descriptor instead.
func (*WorkflowEvent) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowEvent) GetWorkflowID() string {
	if x != nil {
		return x.WorkflowID
	}
	return ""
}

func (x *WorkflowEvent) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *WorkflowEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_UNKNOWN
}

func (x *WorkflowEvent) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *WorkflowEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Flow 引擎发给 Agent 的任务请求
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowID    string                 `protobuf:"bytes,1,opt,name=workflowID,proto3" json:"workflowID,omitempty"`
	TaskID        string                 `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	AgentRole     string                 `protobuf:"bytes,3,opt,name=agentRole,proto3" json:"agentRole,omitempty"`
	Instruction   string                 `protobuf:"bytes,4,opt,name=instruction,proto3" json:"instruction,omitempty"`   // 具体的 Prompt 指令
	InputPayload  []byte                 `protobuf:"bytes,5,opt,name=inputPayload,proto3" json:"inputPayload,omitempty"` // 上游节点传过来的数据
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,7,opt,name=timeoutMs,proto3" json:"timeoutMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRequest) GetWorkflowID() string {
	if x != nil {
		return x.WorkflowID
	}
	return ""
}

func (x *TaskRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskRequest) GetAgentRole() string {
	if x != nil {
		return x.AgentRole
	}
	return ""
}

func (x *TaskRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *TaskRequest) GetInputPayload() []byte {
	if x != nil {
		return x.InputPayload
	}
	return nil
}

func (x *TaskRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Agent 返回给 Flow 引擎的执行结果
type TaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskID           string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Status           TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=zgentflow.TaskStatus" json:"status,omitempty"`
	ResultData       []byte                 `protobuf:"bytes,3,opt,name=resultData,proto3" json:"resultData,omitempty"`     // 成功时返回的业务数据
	ErrorMessage     string                 `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"` // 失败时的报错信息
	PromptTokens     int32                  `protobuf:"varint,5,opt,name=promptTokens,proto3" json:"promptTokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,6,opt,name=completionTokens,proto3" json:"completionTokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_STATUS_UNKNOWN
}

func (x *TaskResponse) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResponse) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TaskResponse) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\tzgentflow\"\xb3\x01\n" +
	"\rWorkflowEvent\x12\x1e\n" +
	"\n" +
	"workflowID\x18\x01 \x01(\tR\n" +
	"workflowID\x12\x16\n" +
	"\x06taskID\x18\x02 \x01(\tR\x06taskID\x122\n" +
	"\teventType\x18\x03 \x01(\x0e2\x14.zgentflow.EventTypeR\teventType\x12\x1c\n" +
	"\ttimeStamp\x18\x04 \x01(\x03R\ttimeStamp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xe7\x01\n" +
	"\vTaskRequest\x12\x1e\n" +
	"\n" +
	"workflowID\x18\x01 \x01(\tR\n" +
	"workflowID\x12\x16\n" +
	"\x06taskID\x18\x02 \x01(\tR\x06taskID\x12\x1c\n" +
	"\tagentRole\x18\x03 \x01(\tR\tagentRole\x12 \n" +
	"\vinstruction\x18\x04 \x01(\tR\vinstruction\x12\"\n" +
	"\finputPayload\x18\x05 \x01(\fR\finputPayload\x12\x1e\n" +
	"\n" +
	"retryCount\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x1c\n" +
	"\ttimeoutMs\x18\a \x01(\x03R\ttimeoutMs\"\xe9\x01\n" +
	"\fTaskResponse\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.zgentflow.TaskStatusR\x06status\x12\x1e\n" +
	"\n" +
	"resultData\x18\x03 \x01(\fR\n" +
	"resultData\x12\"\n" +
	"\ferrorMessage\x18\x04 \x01(\tR\ferrorMessage\x12\"\n" +
	"\fpromptTokens\x18\x05 \x01(\x05R\fpromptTokens\x12*\n" +
	"\x10completionTokens\x18\x06 \x01(\x05R\x10completionTokens*]\n" +
	"\n" +
	"TaskStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x02\x12\x14\n" +
	"\x10STATUS_TOOL_CALL\x10\x03*\xa3\x01\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16EVENT_WORKFLOW_STARTED\x10\x01\x12\x18\n" +
	"\x14EVENT_TASK_SCHEDULED\x10\x02\x12\x18\n" +
	"\x14EVENT_TASK_COMPLETED\x10\x03\x12\x15\n" +
	"\x11EVENT_TASK_FAILED\x10\x04\x12\x1c\n" +
	"\x18EVENT_WORKFLOW_COMPLETED\x10\x052M\n" +
	"\vAgentWorker\x12>\n" +
	"\vExecuteTask\x12\x16.zgentflow.TaskRequest\x1a\x17.zgentflow.TaskResponseB\fZ\n" +
	"./workflowb\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workflow_proto_goTypes = []any{
	(TaskStatus)(0),       // 0: zgentflow.TaskStatus
	(EventType)(0),        // 1: zgentflow.EventType
	(*WorkflowEvent)(nil), // 2: zgentflow.WorkflowEvent
	(*TaskRequest)(nil),   // 3: zgentflow.TaskRequest
	(*TaskResponse)(nil),  // 4: zgentflow.TaskResponse
}
var file_workflow_proto_depIdxs = []int32{
	1, // 0: zgentflow.WorkflowEvent.eventType:type_name -> zgentflow.EventType
	0, // 1: zgentflow.TaskResponse.status:type_name -> zgentflow.TaskStatus
	3, // 2: zgentflow.AgentWorker.ExecuteTask:input_type -> zgentflow.TaskRequest
	4, // 3: zgentflow.AgentWorker.ExecuteTask:output_type -> zgentflow.TaskResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
